let state, plan='all', filter='remaining', query='', selected, fileData, busy=false;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={confirmed:'Confirmed',queued:'Waiting to upload',uploaded:'Uploaded · finish link',linked:'Linked · awaiting confirmation',retry:'Waiting to retry',blocked:'Needs your help'};
function toast(message){$('toast').textContent=message;$('toast').hidden=false;setTimeout(()=>$('toast').hidden=true,5000);}
async function act(body){busy=true;try{const response=await fetch('/api/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw Error(result.error);state=result;render();}catch(e){toast(e.message);}finally{busy=false;}}
function photo(a){return `<div class="photo">${a.media?`<img src="/media/${esc(a.media)}" alt="Photo for pin" loading="lazy">`:'<div class="placeholder">Photo not in local copy</div>'}<div class="photobody"><span class="badge ${esc(a.state)}">${esc(labels[a.state])}</span><small>${esc(a.id)}</small>${a.error?`<p class="error">${esc(a.error)}</p>`:''}${a.state!=='confirmed'?`<button data-retry="${esc(a.id)}" ${state.settings.online!=='true'?'disabled':''}>${a.uploaded?'Finish without re-uploading':'Retry this photo'}</button>${!a.media?`<button data-choose="${esc(a.pin_id)}" data-image="${esc(a.id)}">Choose original photo</button>`:''}<select aria-label="Inject failure for image ${esc(a.id)}" data-fault="${esc(a.id)}"><option value="">No simulated failure</option><option value="after-upload" ${a.fault==='after-upload'?'selected':''}>Lose upload response once</option><option value="confirmation" ${a.fault==='confirmation'?'selected':''}>Fail verification once</option><option value="after-link" ${a.fault==='after-link'?'selected':''}>Lose save response once</option></select>`:''}<small>${a.attempts} attempts · ${(a.bytes_sent/1024).toFixed(0)} KB sent</small></div></div>`;}
function render(){
 $('project').textContent=state.settings.project;$('online').checked=state.settings.online==='true';$('auto').checked=state.settings.auto==='true';
 $('retry-all').disabled=state.remaining===0||state.settings.online!=='true';$('retry-all').textContent=state.settings.online!=='true'?'Waiting for connection':`Retry ${state.remaining} remaining photos`;
 const affected=state.pins.filter(p=>p.images.some(a=>a.state!=='confirmed'));const empty=state.pins.filter(p=>!p.images.length);
 $('summary').innerHTML=`<div class="metric"><strong>${state.confirmed}<span class="muted" style="font-size:15px"> / ${state.total}</span></strong><small>Photos confirmed</small><div class="progress"><span style="width:${state.confirmed/state.total*100}%"></span></div></div><div class="metric warn"><strong>${state.remaining}</strong><small>Photos still to finish</small></div><div class="metric"><strong>${affected.length}</strong><small>Pins affected · ${new Set(affected.map(p=>p.plan)).size} plans</small></div><div class="metric"><strong>${empty.length}</strong><small>Pins without photos · check needed</small></div>`;
 const plans=[...new Set(state.pins.map(p=>p.plan))];$('plans').innerHTML=['all',...plans].map(name=>{const pending=state.pins.filter(p=>name==='all'||p.plan===name).flatMap(p=>p.images).filter(a=>a.state!=='confirmed').length;return `<button class="plan ${plan===name?'active':''}" data-plan="${esc(name)}">${name==='all'?'All plans':esc(name)} <span>${pending||'✓'}</span></button>`;}).join('');
 let pins=state.pins.filter(p=>(plan==='all'||p.plan===plan)&&(!query||`${p.plan} pin ${p.number} ${p.comment}`.toLowerCase().includes(query))&&(filter==='all'||filter==='empty'&&!p.images.length||filter==='remaining'&&p.images.some(a=>a.state!=='confirmed')));
 $('section-title').textContent=filter==='all'?'All pins & photos':filter==='empty'?'Pins to check':'Photos to finish';
 $('pins').innerHTML=pins.map(p=>`<article class="pin"><div class="pinhead"><span class="pinbadge">${esc(p.plan)}</span><strong>Pin ${p.number}</strong><span class="counts">${p.images.filter(a=>a.state==='confirmed').length} / ${p.images.length} photos confirmed</span><button data-choose="${esc(p.id)}">Add photo</button></div>${p.comment?`<p class="pincomment">${esc(p.comment)}</p>`:''}${p.images.length?`<div class="photos">${p.images.map(photo).join('')}</div>`:`<div class="empty-pin"><span>No photo record. Check whether this pin should have one.</span><button data-choose="${esc(p.id)}">Choose photo</button></div>`}</article>`).join('')||'<div class="empty">Nothing needs attention in this view. Use All pins & photos to browse the project.</div>';
 $('events').innerHTML=state.events.map(e=>`<div class="event"><time>${new Date(e.created*1000).toLocaleTimeString()}</time><span>${esc(e.message)}${e.image_id?` <span class="muted">· ${esc(e.image_id)}</span>`:''}</span></div>`).join('');
}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.plan){plan=b.dataset.plan;render();}if(b.dataset.retry)act({action:'retry',ids:[b.dataset.retry]});if(b.dataset.choose){selected={pin_id:b.dataset.choose,id:b.dataset.image};const p=state.pins.find(p=>p.id===selected.pin_id);$('dialog-title').textContent=`${p.plan} · Pin ${p.number}`;$('dialog-description').textContent=selected.id?'Select the original photo for this unfinished image.':'Preview a photo before adding it to this pin in the local copy.';$('file').value='';fileData=null;$('preview').hidden=true;$('queue-photo').disabled=true;$('photo-dialog').showModal();}});
document.addEventListener('change',e=>{if(e.target.dataset.fault)act({action:'fault',id:e.target.dataset.fault,fault:e.target.value});});
$('retry-all').onclick=()=>act({action:'retry'});
$('online').onchange=e=>act({action:'setting',key:'online',value:e.target.checked});
$('auto').onchange=e=>act({action:'setting',key:'auto',value:e.target.checked});
$('reset').onclick=()=>{if(confirm('Reset only this local prototype to the historical nine-photo gap? Your local additions will be removed from the queue.'))act({action:'reset'});};
$('filter').onchange=e=>{filter=e.target.value;render();};$('search').oninput=e=>{query=e.target.value.toLowerCase();render();};
$('file').onchange=e=>{const file=e.target.files[0];if(!file)return;if(file.size>15*1024*1024){toast('Choose a photo under 15 MB');return;}const reader=new FileReader();reader.onload=()=>{fileData=reader.result.split(',')[1];$('preview').src=reader.result;$('preview').hidden=false;$('queue-photo').disabled=false;};reader.readAsDataURL(file);};
$('queue-photo').onclick=async()=>{if(!fileData)return;await act({action:'attach',...selected,data:fileData});$('photo-dialog').close();toast('Photo queued in this local copy');};
async function refresh(){if(busy||$('photo-dialog').open||document.activeElement.tagName==='SELECT')return;try{const response=await fetch('/api/state');if(!response.ok)throw Error('Local server unavailable');state=await response.json();render();}catch(e){toast(e.message);}}
refresh();setInterval(refresh,2000);
