import React, {useEffect,useState} from 'react';
import {database} from '@/services/database';
import useSiteStore from '@/store/useSiteStore';

type Photo={id:string;pin_id:string;state:string;media:string;uploaded:number;error:string;fault:string;attempts:number;bytes_sent:number;test_only?:boolean};
type Pin={id:string;plan:string;number:number;comment:string;images:Photo[]};
type RecoveryProgress={running:boolean;completed:number;total:number;percent:number;message:string;photo:string;image_id?:string};
type Snapshot={progress?:RecoveryProgress;project_id?:string;live_test?:boolean;project_name?:string;pins:Pin[];total:number;confirmed:number;remaining:number;settings:{online:string;auto:string};events:Array<{id:number;message:string}>};
const labels:Record<string,string>={confirmed:'Confirmed',queued:'Waiting to upload',uploaded:'Uploaded — finish link',linked:'Awaiting confirmation',retry:'Waiting to retry',blocked:'Needs your help'};

export default function PhotoRecoveryPrototype({projectId}:{projectId?:string}) {
  const [state,setState]=useState<Snapshot|null>(null),[open,setOpen]=useState(false),[view,setView]=useState('pending'),[plan,setPlan]=useState('all'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [selected,setSelected]=useState<{pin:Pin;id?:string}|null>(null),[photo,setPhoto]=useState('');
  const [actionMessage,setActionMessage]=useState('');
  const refresh=async()=>{try{const r=await fetch('/recovery-api/api/state');if(!r.ok)throw Error('Recovery server unavailable');setState(await r.json());}catch(e){setError(String(e));}};
  useEffect(()=>{refresh();const timer=setInterval(refresh,busy?500:2000);return()=>clearInterval(timer);},[busy]);
  const action=async(body:Record<string,unknown>)=>{setBusy(true);setActionMessage(body.action==='retry'?'Starting photo upload…':body.action==='refresh'?'Checking server photos…':'Saving changes…');setError('');try{const r=await fetch('/recovery-api/api/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await r.json();if(!r.ok)throw Error(result.error);setState(result);return true;}catch(e){setError(String(e));return false;}finally{setBusy(false);setActionMessage('');}};
  if (!projectId||projectId!==(state?.project_id||'proj_1790588796495')||!state) return null;
  const pending=state.pins.filter(p=>p.images.some(a=>a.state!=='confirmed'));
  const visible=state.pins.filter(p=>(plan==='all'||p.plan===plan)&&(view==='all'||view==='empty'&&!p.images.length||view==='pending'&&p.images.some(a=>a.state!=='confirmed')));
  const choose=(pin:Pin,id?:string)=>{setSelected({pin,id});setPhoto('');};
  const uploading=busy||!!state.progress?.running;
  const progress=busy&&!state.progress?.running?undefined:state.progress;
  const feedback=(uploading||progress||state.remaining===0)&&<div role="status" aria-live="polite" className="w-full rounded-lg bg-blue-50 border border-blue-100 p-3">
    <div className="flex gap-2 items-center text-xs text-gray-600 mb-1">{uploading&&<span aria-hidden="true" className="w-4 h-4 shrink-0 border-2 border-blue-500 border-t-transparent rounded-full animate-spin"/>}<span>{progress?.running||!busy?(progress?.message||`All ${state.confirmed} photos confirmed${state.live_test?' on the server':''}.`):actionMessage}</span></div>
    {progress?.photo&&<p className="text-xs text-gray-500 mb-2">{progress.photo}</p>}
    {progress&&<><div role="progressbar" aria-label="Photo upload attempts completed" aria-valuemin={0} aria-valuemax={100} aria-valuenow={progress.percent} className="w-full bg-gray-200 rounded-full h-2"><div className="bg-blue-500 h-2 rounded-full transition-all duration-300" style={{width:`${progress.percent}%`}}/></div><div className="text-xs text-gray-400 mt-1 text-right">{progress.completed} of {progress.total} checked · {progress.percent}%</div></>}
  </div>;
  const queue=async()=>{if(!selected||!photo)return;const pin=selected.pin;const id=selected.id||crypto.randomUUID();if(await action({action:'attach',pin_id:pin.id,id,data:photo.split(',')[1]})){
    if(!(await database.getImagesByPoint(pin.id)).some(a=>a.id===id)){const now=new Date().toISOString();await database.createImage({id,point_id:pin.id,url:photo,created_at:now,updated_at:now,site_visit_number:1});await useSiteStore.getState().loadProjects();}
    setSelected(null);
  }};
  return <>
    <button onClick={()=>setOpen(true)} className="w-full text-left rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900"><strong>{state.remaining?`${state.remaining} photos still to upload`:'All expected photos confirmed'}</strong><span className="block text-xs mt-1">{state.confirmed} of {state.total} confirmed · {pending.length} pins · {new Set(pending.map(p=>p.plan)).size} plans · View details →</span></button>
    {!open&&feedback}
    {open&&<div className="fixed inset-0 bg-black/50 z-[100] flex items-end sm:items-center justify-center"><div role="dialog" aria-modal="true" aria-label="Photo upload status" className="bg-white rounded-t-2xl sm:rounded-xl w-full sm:max-w-xl max-h-[92vh] flex flex-col text-gray-900 shadow-xl">
      <div className="p-4 border-b flex justify-between items-start"><div><h2 className="text-lg font-semibold">Photo upload status</h2><p className="text-xs text-gray-500 mt-1">{state.confirmed} / {state.total} photos confirmed · {state.live_test?'live test database':'local replay'}</p></div><button onClick={()=>setOpen(false)} className="px-3 py-1" aria-label="Close photo status">✕</button></div>
      <div className="p-4 overflow-auto space-y-4"><p className="text-xs text-amber-800 bg-amber-50 p-2 rounded">{state.live_test?'Connected to TEST SYNC in the real database. Only labelled test photos can be added. Existing survey records stay intact.':'Real saved project data. This replays the historical gap; live project status is unchanged.'}</p>
        {feedback}
        <button disabled={uploading||state.remaining===0||state.settings.online!=='true'} onClick={()=>action({action:'retry'})} className="w-full bg-blue-600 text-white rounded-lg py-3 disabled:bg-gray-300">{uploading?'Uploading photos…':state.settings.online!=='true'?'Waiting for connection':state.remaining===0?'All photos confirmed':`Retry ${state.remaining} remaining photos`}</button>
        <div className="flex gap-2"><select aria-label="Photo status filter" value={view} onChange={e=>setView(e.target.value)} className="border rounded p-2 min-w-0 flex-1"><option value="pending">Needs attention</option><option value="all">All pins & photos</option><option value="empty">Pins without photos</option></select><select aria-label="Photo plan filter" value={plan} onChange={e=>setPlan(e.target.value)} className="border rounded p-2 min-w-0 flex-1"><option value="all">All plans</option>{[...new Set(state.pins.map(p=>p.plan))].map(p=><option key={p}>{p}</option>)}</select></div>
        {error&&<p role="alert" className="text-sm text-red-700">{error}</p>}
        {visible.map(pin=><section key={pin.id} className="border rounded-lg p-3"><div className="flex justify-between items-center"><strong className="text-sm">{pin.plan} · Pin {pin.number}</strong><button disabled={state.live_test} onClick={()=>choose(pin)} className="text-blue-600 text-xs disabled:opacity-30">Add photo</button></div><p className="text-xs text-gray-500 my-2">{pin.images.filter(a=>a.state==='confirmed').length} of {pin.images.length} photos confirmed{pin.comment?` · ${pin.comment}`:''}</p>
          {!pin.images.length&&<><p className="text-xs text-gray-600">No photo record. Check whether this pin should have one.</p><button onClick={()=>choose(pin)} className="text-sm text-blue-600 mt-2">Choose photo from this device</button></>}
          <div className="grid grid-cols-2 gap-2">{pin.images.map(a=><div key={a.id} className="border rounded overflow-hidden"><img src={'/recovery-api/media/'+a.media} alt={`${pin.plan} pin ${pin.number} photo`} className="w-full h-28 object-cover"/><div className="p-2">{a.test_only&&<p className="text-xs font-semibold text-purple-700">TEST ONLY · sample photo</p>}<span className={`text-xs font-medium ${a.state==='confirmed'?'text-green-700':'text-amber-800'}`}>{labels[a.state]}</span>{a.error&&<p className="text-xs text-red-700 mt-1">{a.error}</p>}{a.state!=='confirmed'&&<><button disabled={uploading||state.settings.online!=='true'} onClick={()=>action({action:'retry',ids:[a.id]})} className="border rounded text-xs w-full py-2 mt-2 disabled:opacity-40">{uploading&&state.progress?.image_id===a.id?'Uploading…':a.uploaded?'Finish linking photo':'Retry this photo'}</button>{!a.media&&<button onClick={()=>choose(pin,a.id)} className="text-blue-600 text-xs">Choose original</button>}<select aria-label={`Simulate failure ${a.id}`} disabled={uploading} value={a.fault} onChange={e=>action({action:'fault',id:a.id,fault:e.target.value})} className="w-full text-[10px] border rounded p-1 mt-2"><option value="">No simulated failure</option><option value="after-upload">Lose upload response once</option><option value="confirmation">Fail verification once</option><option value="after-link">Lose save response once</option></select></>}<p className="text-[10px] text-gray-400 mt-1">{a.attempts} attempts · {Math.round(a.bytes_sent/1024)} KB sent</p></div></div>)}</div>
        </section>)}
        {!visible.length&&<p className="text-sm text-gray-500">Nothing needs attention in this view.</p>}
        <details className="border-t pt-3 text-xs"><summary className="cursor-pointer">{state.live_test?'Live test controls':'Local recovery controls'}</summary><div className="space-y-3 mt-3"><label className="flex gap-2"><input type="checkbox" checked={state.settings.online==='true'} onChange={e=>action({action:'setting',key:'online',value:e.target.checked})}/>Connection available</label>{!state.live_test&&<label className="flex gap-2"><input type="checkbox" checked={state.settings.auto==='true'} onChange={e=>action({action:'setting',key:'auto',value:e.target.checked})}/>Automatically retry</label>}<button className="text-blue-600" onClick={()=>action({action:state.live_test?'refresh':'reset'})}>{state.live_test?'Refresh from live test database':'Replay historical gap in local queue'}</button><p className="text-gray-500">Native background workers are the next stage. This browser build uses a local persistent worker.</p>{state.events.slice(0,8).map(e=><p key={e.id} className="text-gray-500">{e.message}</p>)}</div></details>
      </div>
    </div></div>}
    {selected&&<div className="fixed inset-0 bg-black/60 z-[110] flex items-center justify-center p-4"><div className="bg-white rounded-xl p-5 w-full max-w-sm text-gray-900"><h3 className="font-semibold">{selected.pin.plan} · Pin {selected.pin.number}</h3><p className="text-xs text-gray-500 my-2">Choose and preview a photo. It will be saved only in this local project copy.</p><input aria-label="Choose pin photo" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>15*1024*1024){setError('Choose a photo under 15 MB');return;}const r=new FileReader();r.onload=()=>setPhoto(String(r.result));r.readAsDataURL(f);}} className="text-xs w-full"/>{photo&&<img src={photo} alt="Selected pin photo preview" className="w-full max-h-60 object-contain my-3"/>}<div className="flex gap-2 mt-4"><button className="border rounded p-2 flex-1" onClick={()=>setSelected(null)}>Cancel</button><button className="bg-blue-600 text-white rounded p-2 flex-1 disabled:opacity-40" disabled={!photo||busy} onClick={queue}>Queue photo</button></div></div></div>}
  </>;
}
